#Arduino parameters
port: '/dev/ttyACM0'
baudrate: 9600

#Trigger information
interval: 120                     #Seconds between stimuli, two minutes should be more than enough
trigger_array:
  -
    - 'a'                        #text command sent to arduino
    - 0                          #shows up in .bag recording file as
  -
    - 'b'                        #text command sent to arduino
    - 100                        #shows up in .bag recording file as, this is a continuous stimulus
  -
    - 'c'                        #text command sent to arduino
    - 200400                    # shows up in .bag file as, in this case 200400 indicates a flicker event with 200ms on period and 400 ms off period (see example firmware)
  -
    - 'd'                        #text command sent to arduino
    - 200200                    #200ms on period 200ms off period (see example firmware)
  -
    - 'e'                        #text command sent to arduino
    - 200100                      #200ms on period 100 ms off period


publisher: '/WalkingArena'     #Specifies the tracking node th


